<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="14252" started-at="2021-07-26T13:04:53 IST" finished-at="2021-07-26T13:05:08 IST">
    <groups>
    </groups>
    <test name="saucedemo" duration-ms="14252" started-at="2021-07-26T13:04:53 IST" finished-at="2021-07-26T13:05:08 IST">
      <class name="saucedemo.LoginTest">
        <test-method status="PASS" signature="Fn_SauceDemoURL()[pri:0, instance:saucedemo.LoginTest@76ed1b7c]" name="Fn_SauceDemoURL" duration-ms="9247" started-at="2021-07-26T13:04:53 IST" finished-at="2021-07-26T13:05:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Fn_SauceDemoURL -->
        <test-method status="PASS" signature="Fn_Login_Validation()[pri:0, instance:saucedemo.LoginTest@76ed1b7c]" name="Fn_Login_Validation" duration-ms="3344" started-at="2021-07-26T13:05:04 IST" depends-on-methods="saucedemo.LoginTest.Fn_SauceDemoURL" finished-at="2021-07-26T13:05:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Fn_Login_Validation -->
      </class> <!-- saucedemo.LoginTest -->
      <class name="saucedemo.ProductTest">
        <test-method status="FAIL" signature="Fn_Products_Validation_Adding()[pri:0, instance:saucedemo.ProductTest@1018bde2]" name="Fn_Products_Validation_Adding" duration-ms="1" started-at="2021-07-26T13:05:08 IST" finished-at="2021-07-26T13:05:08 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at SaucedemoObjects.ProductsObjects.Fn_Product_Name(ProductsObjects.java:32)
at saucedemo.ProductTest.Fn_Products_Validation_Adding(ProductTest.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Fn_Products_Validation_Adding -->
      </class> <!-- saucedemo.ProductTest -->
    </test> <!-- saucedemo -->
  </suite> <!-- Suite -->
</testng-results>
